.TH uget-chrome-wrapper 1 "October 2, 2016"
.SH NAME
uget-chrome-wrapper \- Integrate uGet Download Manager with Google Chrome
.SH SYNOPSIS
/usr/bin/uget-chrome-wrapper
.SH DESCRIPTION
uget-chrome-wrapper (full name: uGet Chrome Wrapper) is a background script which integrates uGet Download Manager with Google Chrome
.SH AUTHOR
uGet Chrome Wrapper is written by Loganathan Gobinath (slgobinath@gmail.com)
.SH BUGS
If you find a bug, please report it at https://github.com/slgobinath/uget-chrome-wrapper/issues
